Resolves #34 create checkboxes using an object
plocket/docassemble-ALAutomatedTestingTests pull request #36
Opened 2021-02-15 02:23 UTC by jessehall3

This adds a new page with checkboxes that uses a value from a variable in a code block. This is meant to fulfill issue #34. Please let me know if this is what was intended -- I'm not certain myself.

2021-02-15 15:34 UTC, plocket requested changes
It's a good start. We should talk about this more in real-time to go over docassemble behavior a bit.

2021-02-15 15:34 UTC, plocket commented on docassemble/ALAutomatedTestingTests/data/questions/all_tests.yml
> +  Some fields 1
Avoid editing these blocks as other people have edited them and it may create a conflict.

2021-02-16 22:16 UTC, jessehall3 commented
@plocket 
I made the changes we discussed with one big expectation -- I could not get `source: actors` (which makes use of a DAList) to work as before, only.
```
choices:
    - protagonist
    - antagonist
```

What seems clear is that it was working before when `choices` was defined in a previous question using the objects one by one. After that, I could get the DAList to work. :man_shrugging:

2021-03-04 13:01 UTC, plocket commented
> I could not get source: actors (which makes use of a DAList) to work as before, only.

This is great as it is, no worries at all. We might add a separate issue to research one created with a single object to see if the DOM is different there.

2021-03-04 13:05 UTC, plocket approved these changes
This is fantastic and has already revealed that we're missing a step here!

To put in an issue: It looks like a choice's `name` is basically triple encoded as opposed to the usual double encoding - the value inside `[B'encoded_value']` is, when decoded, still needs to be decoded one more time. What a world!

2021-03-04 13:05 UTC, merged